### ISSUE TITLE
getting "Namespace 'firebase' has no exported member 'Promise'.ts(2694)" error while compiling

### ISSUE THREAD

**Issue by sumanthkasula** [hamzahamidi/angular-forum#22]
import * as firebase from 'firebase/app';
import { Observable } from 'rxjs/Observable';
export interface FirebaseAppConfig {
    apiKey?: string;
    authDomain?: string;
    databaseURL?: string;
    storageBucket?: string;
    messagingSenderId?: string;
    projectId?: string;
}
export interface FirebaseOperationCases {
    stringCase: () => firebase.Promise<void>;
    firebaseCase?: () => firebase.Promise<void>;
    snapshotCase?: () => firebase.Promise<void>;
    unwrappedSnapshotCase?: () => firebase.Promise<void>;

Fire base version:  7.13.0
Node version: v10.16.3

**Comment by hamzahamidi** [comment]
I don't understand this issue. This project doesn't use firebase.
